spring:
  application:
    name: auction

  config:
    import: optional:application-secret.yml

  jwt:
    secret-key: ${jwt.secret-key}
    access-token-validity-seconds: ${jwt.access-token-validity-seconds}
    refresh-token-validity-seconds: ${jwt.refresh-token-validity-seconds}

  kakao:
    mobility:
      base-url: https://apis-navi:kakaomobility:com/v1/directions
      rest-api-key: ${kakao.mobility.rest-api-key}

  vword:
    base-url: https://api.vworld.kr/req/address
    rest-api-key: ${vword.rest-api-key}

  redis:
    host: redis

  rabbitmq:
    host: rabbitmq